import mongoose from 'mongoose';
import { Router } from 'express';
import { Attempt, IAttempt } from '../models/Attempt.js';
import { Student } from '../models/Student.js';
import { GradingService } from '../services/gradingService.js';
import { optionalAuth, AuthenticatedRequest, AuthenticatedStudent } from '../middlewares/authMiddleware.js';
import { db } from '../../server/db.js';

const router = Router();

// POST /api/attempts - Submit Attempt & Authoritative Server Grading
router.post('/', optionalAuth, async (req: AuthenticatedRequest, res) => {
  try {
    const {
      topicId,
      topicName,
      subjectId,
      bloomLevel,
      testCode,
      timeTakenSeconds,
      answers,
      studentRoll,
      studentName,
      studentDepartment,
      studentEmail,
    } = req.body;

    if (!answers || !Array.isArray(answers) || answers.length === 0) {
      return res.status(400).json({ error: 'No answers provided for evaluation.' });
    }

    // Determine authoritative student
    let activeStudent: AuthenticatedStudent | null = req.student || null;

    const cleanRoll = String(studentRoll || (activeStudent?.rollNumber) || 'CANDIDATE').trim().toUpperCase();
    const cleanName = String(studentName || (activeStudent?.name) || cleanRoll).trim();
    const cleanDept = String(studentDepartment || (activeStudent?.department) || 'Computer Science & Engineering').trim();
    const cleanEmail = String(studentEmail || (activeStudent?.email) || `${cleanRoll.toLowerCase()}@kongu.edu`).trim();

    if (!activeStudent && cleanRoll) {
      // 1. Fallback lookup from MongoDB student record if JWT header was missed
      try {
        const studentDoc = await Student.findOne({ rollNumber: cleanRoll });
        if (studentDoc) {
          activeStudent = {
            id: studentDoc._id.toString(),
            rollNumber: studentDoc.rollNumber,
            name: studentDoc.name,
            email: studentDoc.email,
            department: studentDoc.department,
          };
        }
      } catch (dbErr) {
        console.warn('Notice: MongoDB student lookup failed:', dbErr);
      }

      // 2. Fallback to local persistent user store
      if (!activeStudent) {
        const localUser = db.getUserByRoll(cleanRoll);
        if (localUser) {
          activeStudent = {
            id: localUser.id || new mongoose.Types.ObjectId().toString(),
            rollNumber: localUser.roll,
            name: localUser.name,
            email: localUser.email,
            department: localUser.department,
          };
        }
      }

      // 3. Auto-register student identity so concurrent classroom/test-takers never fail
      if (!activeStudent) {
        const generatedObjId = new mongoose.Types.ObjectId();
        activeStudent = {
          id: generatedObjId.toString(),
          rollNumber: cleanRoll,
          name: cleanName,
          email: cleanEmail,
          department: cleanDept,
        };

        // Try upserting to MongoDB
        try {
          await Student.create({
            _id: generatedObjId,
            rollNumber: cleanRoll,
            name: cleanName,
            email: cleanEmail,
            department: cleanDept,
            passwordHash: 'AUTOGENERATED_CANDIDATE_SESSION',
            isInstitutionalEmail: true,
            emailVerified: true,
          });
        } catch {
          // Handled smoothly
        }

        // Also save to local database
        try {
          db.createUser({
            roll: cleanRoll,
            name: cleanName,
            email: cleanEmail,
            department: cleanDept,
          });
        } catch {
          // Handled smoothly
        }
      }
    }

    if (!activeStudent) {
      const fallbackObjId = new mongoose.Types.ObjectId();
      activeStudent = {
        id: fallbackObjId.toString(),
        rollNumber: 'CANDIDATE',
        name: 'Student Candidate',
        email: 'candidate@kongu.edu',
        department: 'Engineering',
      };
    }

    const attempt = await GradingService.evaluateAndSaveAttempt({
      student: activeStudent,
      testCode: testCode || 'APT-GENERAL',
      topicId: topicId || 'topic-general',
      topicName,
      subjectId,
      bloomLevel,
      timeTakenSeconds: Number(timeTakenSeconds) || 0,
      answers,
    });

    res.status(201).json({
      success: true,
      attemptId: (attempt as any)._id?.toString() || (attempt as any).id,
      testCode: attempt.testCode,
      score: attempt.score,
      total: attempt.total,
      percentage: attempt.percentage,
    });
  } catch (err: any) {
    console.error('Error in attempt submission:', err);
    res.status(500).json({ error: err.message || 'Failed to evaluate attempt' });
  }
});

// GET /api/attempts - Get all attempts (with optional filters)
router.get('/', async (req, res) => {
  try {
    const { topicId, subjectId, testCode, studentRoll } = req.query;
    const filter: any = {};

    if (topicId && topicId !== 'all') filter.topicId = String(topicId);
    if (subjectId && subjectId !== 'all') filter.subjectId = String(subjectId);
    if (testCode && testCode !== 'all') filter.testCode = String(testCode).toUpperCase();
    if (studentRoll) filter.studentRoll = String(studentRoll).toUpperCase();

    const attempts = await Attempt.find(filter)
      .sort({ submittedAt: -1 })
      .limit(100)
      .lean();

    res.json(
      attempts.map((a: any) => ({
        id: a._id.toString(),
        topicId: a.topicId,
        topicName: a.topicName,
        subjectId: a.subjectId,
        testCode: a.testCode,
        bloomLevel: a.bloomLevel,
        studentName: a.studentName,
        studentRoll: a.studentRoll,
        studentEmail: a.studentEmail,
        studentDepartment: a.studentDepartment,
        score: a.score,
        total: a.total,
        percentage: a.percentage,
        timeTakenSeconds: a.timeTakenSeconds,
        answers: a.answers,
        createdAt: (a.submittedAt || a.createdAt).toISOString(),
      }))
    );
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// GET /api/attempts/:id - Get Attempt by ID
router.get('/:id', async (req, res) => {
  try {
    const { id } = req.params;
    let attempt: any = null;

    // 1. Try querying MongoDB if available
    try {
      if (id.match(/^[0-9a-fA-F]{24}$/)) {
        attempt = await Attempt.findById(id).lean();
      }
      if (!attempt) {
        attempt = await Attempt.findOne({ $or: [{ testCode: id.toUpperCase() }, { id }] }).lean();
      }
    } catch {
      // Handled smoothly
    }

    // 2. Fallback to local persistent database
    if (!attempt) {
      const local = db.getAttemptById(id) || db.getAttempts().find(
        (a: any) => String(a.id || a._id) === id || String(a.testCode || '').toUpperCase() === id.toUpperCase()
      );
      if (local) {
        attempt = local;
      }
    }

    if (!attempt) {
      return res.status(404).json({ error: 'Attempt record not found' });
    }

    const a = attempt as any;
    res.json({
      id: (a._id ? a._id.toString() : a.id) || id,
      topicId: a.topicId,
      topicName: a.topicName,
      subjectId: a.subjectId || 'subj-aptitude',
      testCode: a.testCode,
      bloomLevel: a.bloomLevel || 'Apply',
      studentName: a.studentName || 'Student Candidate',
      studentRoll: a.studentRoll || 'CANDIDATE',
      studentEmail: a.studentEmail || `${(a.studentRoll || 'candidate').toLowerCase()}@kongu.edu`,
      studentDepartment: a.studentDepartment || 'Engineering',
      score: a.score,
      total: a.total,
      percentage: a.percentage ?? Math.round((a.score / Math.max(1, a.total)) * 100),
      timeTakenSeconds: a.timeTakenSeconds || 0,
      answers: a.answers || [],
      bloomBreakdown: a.bloomBreakdown,
      createdAt: (a.submittedAt || a.createdAt || new Date()).toISOString ? (a.submittedAt || a.createdAt).toISOString() : new Date().toISOString(),
    });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

export default router;
